// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbcahmtswzjfkxhrfpkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiY2FobXRzd3pqZmt4aHJmcGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MDA5MTYsImV4cCI6MjA3OTA3NjkxNn0.vttm9WiY1VgLgkbnyxhh0p9XReJs8-2mLVkL5h0qo0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});